name: main

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Node.js to 16.x
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16.x

      - name: Install dependencies
        run: |
          npm install --location=global yarn
          yarn install
          yarn global add typescript
      - name: Check TypeScript syntax
        run: |
          tsc